import { Geist, Geist_Mono } from 'next/font/google'
import Head from 'next/head'
import React from 'react'
import Link from 'next/link'
import ProfileLayout from './profile.layout'
import AboutLayout from './about.layout'
import FileLayout from './file.layout'
import { useRouter } from 'next/router'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export default function MainLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const router = useRouter()
  const path = router?.pathname || ''

  const renderLayout = (path: string, children: React.ReactNode) => {
    if (path === '/profile') return <ProfileLayout>{children}</ProfileLayout>
    if (path === '/about') return <AboutLayout>{children}</AboutLayout>
    if (path === '/file') return <FileLayout>{children}</FileLayout>
    return children
  }

  return (
    <>
      <Head>
        <title>Nextjs Course</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col min-h-screen`}
      >
        <header className="bg-blue-600 text-white p-4">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-xl font-bold">Next.js App</h1>
            <ul className="flex space-x-4">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/about">About</Link>
              </li>
              <li>
                <Link href="/profile">Profile</Link>
              </li>
            </ul>
          </div>
        </header>
        <main className="flex-1 container mx-auto p-4">
          {renderLayout(path, children)}
        </main>
      </div>
    </>
  )
}
