name: Deploy vercel on taging

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger from deployment hook
        run: |
          curl -X POST https://api.vercel.com/v1/integrations/deploy/prj_cvP6GWmzNA0XtTBaRhQRxS4D8nGs/BEvIWB8NH1
